/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ShipRouteImport } from './routes/ship'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiByokRouteImport } from './routes/api/byok'
import { Route as ApiGroundRouteImport } from './routes/api/ground'
import { Route as ApiImagineRouteImport } from './routes/api/imagine'
import { Route as ApiMeshRouteImport } from './routes/api/mesh'
import { Route as ApiOwnerRouteImport } from './routes/api/owner'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingEnsureCustomerRouteImport } from './routes/api/billing/ensure-customer'
import { Route as ApiMeterIndexRouteImport } from './routes/api/meter/index'
import { Route as ApiMeterDebitRouteImport } from './routes/api/meter/debit'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipRoute = ShipRouteImport.update({
  id: '/ship',
  path: '/ship',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiByokRoute = ApiByokRouteImport.update({
  id: '/api/byok',
  path: '/api/byok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroundRoute = ApiGroundRouteImport.update({
  id: '/api/ground',
  path: '/api/ground',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagineRoute = ApiImagineRouteImport.update({
  id: '/api/imagine',
  path: '/api/imagine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeshRoute = ApiMeshRouteImport.update({
  id: '/api/mesh',
  path: '/api/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOwnerRoute = ApiOwnerRouteImport.update({
  id: '/api/owner',
  path: '/api/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingEnsureCustomerRoute =
  ApiBillingEnsureCustomerRouteImport.update({
    id: '/api/billing/ensure-customer',
    path: '/api/billing/ensure-customer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeterIndexRoute = ApiMeterIndexRouteImport.update({
  id: '/api/meter/',
  path: '/api/meter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeterDebitRoute = ApiMeterDebitRouteImport.update({
  id: '/api/meter/debit',
  path: '/api/meter/debit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/ship': typeof ShipRoute
  '/terms': typeof TermsRoute
  '/api/byok': typeof ApiByokRoute
  '/api/ground': typeof ApiGroundRoute
  '/api/imagine': typeof ApiImagineRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/owner': typeof ApiOwnerRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/r/$code': typeof RCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/ensure-customer': typeof ApiBillingEnsureCustomerRoute
  '/api/meter/debit': typeof ApiMeterDebitRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/meter/': typeof ApiMeterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/ship': typeof ShipRoute
  '/terms': typeof TermsRoute
  '/api/byok': typeof ApiByokRoute
  '/api/ground': typeof ApiGroundRoute
  '/api/imagine': typeof ApiImagineRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/owner': typeof ApiOwnerRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/r/$code': typeof RCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/ensure-customer': typeof ApiBillingEnsureCustomerRoute
  '/api/meter/debit': typeof ApiMeterDebitRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/meter': typeof ApiMeterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/plugins': typeof PluginsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/ship': typeof ShipRoute
  '/terms': typeof TermsRoute
  '/api/byok': typeof ApiByokRoute
  '/api/ground': typeof ApiGroundRoute
  '/api/imagine': typeof ApiImagineRoute
  '/api/mesh': typeof ApiMeshRoute
  '/api/owner': typeof ApiOwnerRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/r/$code': typeof RCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/ensure-customer': typeof ApiBillingEnsureCustomerRoute
  '/api/meter/debit': typeof ApiMeterDebitRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/meter/': typeof ApiMeterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/contact'
    | '/faq'
    | '/login'
    | '/plugins'
    | '/pricing'
    | '/privacy'
    | '/referrals'
    | '/ship'
    | '/terms'
    | '/api/byok'
    | '/api/ground'
    | '/api/imagine'
    | '/api/mesh'
    | '/api/owner'
    | '/api/referrals'
    | '/r/$code'
    | '/api/auth/$'
    | '/api/billing/ensure-customer'
    | '/api/meter/debit'
    | '/api/stripe/webhook'
    | '/api/meter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/contact'
    | '/faq'
    | '/login'
    | '/plugins'
    | '/pricing'
    | '/privacy'
    | '/referrals'
    | '/ship'
    | '/terms'
    | '/api/byok'
    | '/api/ground'
    | '/api/imagine'
    | '/api/mesh'
    | '/api/owner'
    | '/api/referrals'
    | '/r/$code'
    | '/api/auth/$'
    | '/api/billing/ensure-customer'
    | '/api/meter/debit'
    | '/api/stripe/webhook'
    | '/api/meter'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/contact'
    | '/faq'
    | '/login'
    | '/plugins'
    | '/pricing'
    | '/privacy'
    | '/referrals'
    | '/ship'
    | '/terms'
    | '/api/byok'
    | '/api/ground'
    | '/api/imagine'
    | '/api/mesh'
    | '/api/owner'
    | '/api/referrals'
    | '/r/$code'
    | '/api/auth/$'
    | '/api/billing/ensure-customer'
    | '/api/meter/debit'
    | '/api/stripe/webhook'
    | '/api/meter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PluginsRoute: typeof PluginsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferralsRoute: typeof ReferralsRoute
  ShipRoute: typeof ShipRoute
  TermsRoute: typeof TermsRoute
  ApiByokRoute: typeof ApiByokRoute
  ApiGroundRoute: typeof ApiGroundRoute
  ApiImagineRoute: typeof ApiImagineRoute
  ApiMeshRoute: typeof ApiMeshRoute
  ApiOwnerRoute: typeof ApiOwnerRoute
  ApiReferralsRoute: typeof ApiReferralsRoute
  RCodeRoute: typeof RCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingEnsureCustomerRoute: typeof ApiBillingEnsureCustomerRoute
  ApiMeterDebitRoute: typeof ApiMeterDebitRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiMeterIndexRoute: typeof ApiMeterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ship': {
      id: '/ship'
      path: '/ship'
      fullPath: '/ship'
      preLoaderRoute: typeof ShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/byok': {
      id: '/api/byok'
      path: '/api/byok'
      fullPath: '/api/byok'
      preLoaderRoute: typeof ApiByokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ground': {
      id: '/api/ground'
      path: '/api/ground'
      fullPath: '/api/ground'
      preLoaderRoute: typeof ApiGroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imagine': {
      id: '/api/imagine'
      path: '/api/imagine'
      fullPath: '/api/imagine'
      preLoaderRoute: typeof ApiImagineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesh': {
      id: '/api/mesh'
      path: '/api/mesh'
      fullPath: '/api/mesh'
      preLoaderRoute: typeof ApiMeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/owner': {
      id: '/api/owner'
      path: '/api/owner'
      fullPath: '/api/owner'
      preLoaderRoute: typeof ApiOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/ensure-customer': {
      id: '/api/billing/ensure-customer'
      path: '/api/billing/ensure-customer'
      fullPath: '/api/billing/ensure-customer'
      preLoaderRoute: typeof ApiBillingEnsureCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meter/': {
      id: '/api/meter/'
      path: '/api/meter'
      fullPath: '/api/meter/'
      preLoaderRoute: typeof ApiMeterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meter/debit': {
      id: '/api/meter/debit'
      path: '/api/meter/debit'
      fullPath: '/api/meter/debit'
      preLoaderRoute: typeof ApiMeterDebitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PluginsRoute: PluginsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReferralsRoute: ReferralsRoute,
  ShipRoute: ShipRoute,
  TermsRoute: TermsRoute,
  ApiByokRoute: ApiByokRoute,
  ApiGroundRoute: ApiGroundRoute,
  ApiImagineRoute: ApiImagineRoute,
  ApiMeshRoute: ApiMeshRoute,
  ApiOwnerRoute: ApiOwnerRoute,
  ApiReferralsRoute: ApiReferralsRoute,
  RCodeRoute: RCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingEnsureCustomerRoute: ApiBillingEnsureCustomerRoute,
  ApiMeterDebitRoute: ApiMeterDebitRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiMeterIndexRoute: ApiMeterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
